// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwopzWmiMZKpdR10MK_qFg8ZcL_ktuuac',
    appId: '1:609309128387:web:bef4ab6f3cf0fb7e5a1476',
    messagingSenderId: '609309128387',
    projectId: 'doanmobile-ac032',
    authDomain: 'doanmobile-ac032.firebaseapp.com',
    storageBucket: 'doanmobile-ac032.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnXydooSBFUlJ3Y-olBrLibPjuRa-0zg',
    appId: '1:609309128387:android:a327528afcc08f7e5a1476',
    messagingSenderId: '609309128387',
    projectId: 'doanmobile-ac032',
    storageBucket: 'doanmobile-ac032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmfatqbP0EIOXzO_009kQd_ofWTxuwYM',
    appId: '1:609309128387:ios:3fa5f0624492f2255a1476',
    messagingSenderId: '609309128387',
    projectId: 'doanmobile-ac032',
    storageBucket: 'doanmobile-ac032.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmfatqbP0EIOXzO_009kQd_ofWTxuwYM',
    appId: '1:609309128387:ios:3fa5f0624492f2255a1476',
    messagingSenderId: '609309128387',
    projectId: 'doanmobile-ac032',
    storageBucket: 'doanmobile-ac032.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwopzWmiMZKpdR10MK_qFg8ZcL_ktuuac',
    appId: '1:609309128387:web:2ff65ab5779966ee5a1476',
    messagingSenderId: '609309128387',
    projectId: 'doanmobile-ac032',
    authDomain: 'doanmobile-ac032.firebaseapp.com',
    storageBucket: 'doanmobile-ac032.firebasestorage.app',
  );
}
